/*
 * This source file was generated by the Gradle 'init' task
 */
package db_lab;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public final class AppTest {
    @Test
    public void test() {
        assertNotNull(69);
    }
}
